### ISSUE TITLE
feature: add option --lc_collate

### ISSUE THREAD

**Issue by masaoliou** [debops/ansible-postgresql_server#24]
It will be nice to have a variable which will be passed as option *--lc_collate=* to both commands *pg_createcluster* and *createdb*.

I am likely to set *"C"* to this variable in most cases.

**Comment by drybjed** [comment]
Sure, a variable for that can be added. Is there an important difference between `--lc_collate` and `--locale`? Currently role sets up the databases and clusters so that UTF-8 is the default encoding everywhere, does that make sense with `--lc_collate`?

**Comment by masaoliou** [comment]
You are right! `--locale` suffices. There is no need to add the additional `--lc_collate` option.
I am closing this feature request.

**Comment by masaoliou** [comment]
Oops! Perhaps I have to reopen this issue.
The ultimate additional option I need probably is `--encoding=`.

I am trying to use locale `C` with encoding `UTF8` for this moment:

````shell
pg_createcluster --locale=C --encoding=UTF-8
````

Next time I probably will need these:

````shell
pg_createcluster --locale=C.UTF-8 --encoding=UTF-8
pg_createcluster --locale=zh_TW.utf8 --encoding=UTF-8
pg_createcluster --locale=zh_CN.utf8 --encoding=UTF-8
````
